BEGIN;

TRUNCATE TABLE
  tools
  RESTART IDENTITY CASCADE;

INSERT INTO tools (tool_name, tool_category, tool_desc ,tool_img_filename, tool_img_alt)
VALUES
("claw hammer", "hammers", "fiberglass claw hammer", "husky-claw-hammers.jpg", "claw hammer with fiberglass handle"),
("framing hammer-checkered face", "hammers","steel checkered-face hammer","steel-checkered-face-hammer.jpg", "steel-checkered-face framing hammer"),
("framing hammer-milled face", "hammers","steel hammer, shock reduction, milled face","milled-face-framing-hammer.jpg", "steel-milled-face framing hammer"),
("soft hammer, double faced", "hammers","two sided hammer, one soft face, one hard faced with hickory handle","-soft-double-faced-hammer.jpg", "double headed hammer, one head red, one head yellow, with a hickory handle. can be  used for soft or hard needs"),
("Engineer hammer", "hammers","steel double sided hammer","engineer-hammer.jpg", "steel double faced engineer hammer with yellow fiberglass handle"),
("blacksmith steel hammer", "hammers","64 oz. steel blacksmith hammer", "steel-blacksmith-hammer.jpg", "steelblacksmithing hammer with one head blunt the other comes to a point"),
("Bricklayer hammer", "hammers","Smooth-faced double-tempered head and decreased shock with nylon wrapped handle","bricklayers-hammer.jpg", "flat faced, hammer, in blue with shock reducing wrapped handle"),
("Demolition hammer", "hammers","enlarged claw, 22 oz. steel head 9.25in handle","demolition-hammer.jpg", "demolition hammer, with hollow handle, enlarged claw"),
("tack hammer", "hammers","magnetic, hickory handle, small double headed mallet","tack-hammer.jpg", "hickory wood handle, small, double headed mallet for tacks"),
("Tinners hammer", "hammers","one piece construction to set rivets,  hammer", "Tinners-hammer.jpg", "one piece, polished steel hammer for setting rivets"),
("Fence Post Pounder hammer", "hammers","27 lb. fence post hammer", "post-pounder-hammer.jpg", "Post punder hammer, with two long handles and can be used by two people"),
("tin snips", "cutting tools","compund action straight, right, and left cut snips", "tin-snips.jpg", "yellow handled tin snips with safety latch"),
("Pick Mattock", "cutting tools","single injection fiberglass, 2.5 pounds", "pick-mattock.jpg", "2.5 pound long black handled pick mattock"),
("High tension hack saw", "cutting tools","contractor grade saw, cuts metal and plastic. 45 and 90 degree angles","contractor-hack-saw.jpg", "yellow and black handled hacksaw"),
("3in. straight cut aviation snip", "cutting tools","forged blades and bolt lock to keep blades from loosening","aviation-snip.jpg", "red handled aviation snip"),
("Bolt Cutters", "cutting tools","lightweight 24 inch bolt cutters", "bolt-cutters.jpg", "black bolt cutters, 24 inches, blue and black handles"),
("Machete", "cutting tools","24 inch machete, great for cutting thick brush, can be used one or two handed", "machete.jpg", "24 inch machete with holes in blade and black and orange grip"),
("Jab saw", "cutting tools","tempered steel,punches and cuts through drywall with ease. Also great for cutting through wood and plywood.", "jab-saw.jpg", "red rubber handled jab saw"),
("Log splitter", "cutting tools","34 in. fiberglass handle, 4lb log splitter", "log-splitter-34inch.jpg", "black fiberglass handled log splitter"),
("Splitting maul", "cutting tools","8 lb. 34inch splitting maul with fiberglass handle", "splitting-maul-34inch.jpg", "black fiber glass handled 34 inch splitting maul"),
("Cutter Mattock", "cutting tools","fiberglass handle, 36 inches, 5lbs", "cutter-mattock-5lbs.jpg", "36 inch lack fiberglass handled cutting mattock"),
("Single Bit Axe", "cutting tools","laser etched grip for control, 4 lbs, 35 in hickory axe", "axe-4lbs.jpg", "35 inch hickory handled axe with laser etched handle"),
("camp axe", "cutting tools","1 1/4 lbs camp axe with fiberglas handle(14in.)", "camp-axe.jpg", "14 inch fiberglass handle, black, camp axe"),
("Tooth saw", "cutting tools","15 inch tooth saw, aluminum handle", "src/imgs/tooth-saw.jpg", "traditional hand saw, 15 inches, black and gold handle"),
("Coping Saw", "cutting tools","adjustable blade, allows for 360 degree cuts, heavy duty steel frame", "src/imgs/coping-saw.jpg", "wood handled 6 inch coping saw"),
("Cordless drill/driver, 18 volt", "electric drills","shared with lithium ion battery, charger, and bag. Bits are seperate.", "cordless-power-drill.jpg", "black and yellow drill/driver with bag, two batteries, and charger"),
("Cordless impact driver", "electric drills","18 volt lithium ion brushless impact driver with one battery and charger, plus bag. bits are not included.", "cordless-impact-driver.jpg", "Blue and black color scheme for bag, impact driver, one battery and charger"),
("Hammer Drills", "electric drills","1/2 inch variable speed, reversable hammer drill, 2700 rpm amd 8 ft cord",    "hammer-drill.jpg", "black and gold hammer driver"),
("Rotary hammer driver", "electric drills","e-clutch 15 amp 1-3/4 in corded combimation hammer. 8.1 ft-lbs of impact", "rotary-hammers.jpg", "red and black rotary hammer driver"),
("Circular saw, cordless-Tool only", "electric saws","20-Volt motor delivers up to 460 MWO and 5,150 RPM, Up to 50 degree bevel cut capacity,2-1/4 in. cutting capacity at 90 degree  ", "cordless-circular-saw.jpg", "black and gold cordless circular saw"),
("cordless 4-1/2 inch circular saw-Tool Only", "electric saws","20-Volt motor delivers up to 800 MWO and 4500 RPM, p to 45 degree bevel cut capacity", "circular-saw4in.jpg", "black and gold cordless 4 1/2inch circular saw"),
("circular saw, corded with hard case", "electric saws","15 Amp, 3.25 peak horsepower motor,
", "corded-circular-saw.jpg", "red and silvar circular saw and hard case in red"),
("reciprocating saw, cordless", "electric saws","20 volt litium ion cordless recipricating saw Tool-Only. Variable speed trigger, keyless blade change", "cordless-recipricating-saw.jpg", "yellow and black reciprocating saw"),
("sawzall reciprocating saw with cord", "electric saws","12 amps reciprocating saw, redesigned front grip, 1-11/8th in stroke length with clutch", "corded-reciprocating-saw.jpg", "reg and grey reciprocating saw with cord"),
("Table saw", "electric saws","15 amp 10inch table saw with rolling stand, push stick, and miter gauge", "portable-table-saws.jpg", "yellow and black table saw with rolling stand"),
("jig saw, cordless", "electric saws","18 volt litium ion battert, cordless jigsaw. Works on hardwoods, metal, other hard materials. Uses t-shank jig saw blades (not included)", "cordless-jigsaw.jpg", "red and black cordless jigsaw"),
("jigsaw, corded 6.5 amp", "electric saws","8.5 amp motor, 4 position orbital action, keyless show bevel, lever-action blade clamp and dust blower", "corded-jigsaw.jpg", "black and gold corded jigsaw (blades not included"),
("grinder, cordless", "power grinders","18-Volt Lithium-Ion Brushless Cordless 4-1/2 in. / 5 in. Grinder with Paddle Switch (Tool-Only)", "cordless-grinder.jpg", "red and black power grinder, cordless"),
("cut off/angle grinder, cordless", "power grinders","18-Volt LXT Lithium-Ion Brushless Cordless 4-1/2 in./5 in. Cut-Off/Angle Grinder (Tool-Only)", "angle-grinder-cordless.jpg", "blue and silver cordless grinder"),
("belt sander, cordless", "sanders","18-Volt GEN5X Cordless Brushless 3 in. x 18 in. Belt Sander (Tool Only) with Dust Bag and (1) 80 Grit Sanding Belt, Tool-free sanding belt release for easy changes, Features an integrated vac adaptor for dust-free results", "steel-checkered-face-hammer.jpg", "steel-checkered-face framing hammer"),
("framing hammer", "hammers","steel checkered-face hammer", "cordless-belt-sander.jpg", "orange and black belt sander, cordless"),
("belt sander, corded", "sanders","11 Amp 4 in. x 24 in. Corded Belt Sander with Abrasive Belt, 80G Belt and Dust Bag,16.2 ft cord for maneuverability and large front grip for comfort", "belt-sander.jpg", "blue belt sander with red dust bag"),
("orbital sander, corded", "sanders","3 Amp Corded 5 in. Random Orbital Sander with AIRGUARD Technology, Airguard dust collection system gathers up to 90% of the dust, Soft start and pad brake to help prevent gouges", "disc-orbital-sanders-corded.jpg", "orange orbital sander, corded"),
("orbital sander, cordless", "sanders","18-Volt Lithium-Ion Cordless 5 in. Random Orbit Sander (Tool-Only), 12,000 OPM Max with Variable Speed Control", "steel-checkered-face-hammer.jpg", "red and black orbital sander, cordless, with battery, dustbag, and sanding pad"),
("electric chainsaw, corded", "chain saws","18 in. 15 Amp Self Sharpening Electric Chainsaw, features a chain that can sharpen itself. The 15 Amp high-powered motor offers fast cutting with an 18 in. (45 cm) reduced-kickback guide bar and chain.", "electric-chainsaw-corded.jpg", "silver and black electric chain saw with cord"),
("chainsaw, cordless", "chainsaws","20-Volt MAX Lithium-Ion Cordless 12 in. Brushless Chainsaw w/ (1) 5.0Ah Battery and Charger, OREGON bar and chain are low-kickback and automatically oiled", "chainsaws-cordless.jpg", "gold and black cordless electric chainsaw"),
("chainsaw, gas-powered", "chainsaws","14 in. 37cc 2-Cycle Gas Chainsaw, 3-point vibration isolation increases comfort and reduces fatigue, Automatic oiler for smooth operation  ", "gas-chainsaw.jpg", "green and black gas powered chainsaw, 14inch bar"),
("powerwasher, electric, 2,000 PSI", "pressure washers","1.2 GPM Electric Pressure Washer, Powerful 13 Amp Motor Handles Tough Jobs", "src/imgs/electric-power-washer.jpg", "powerwasher black handled, white hose, green body on wheels"),
("powerwasher, electric, 1500 PSI", "pressure washers","120 Volt Heavy Duty Induction Motor,General Pump Triplex Plunger Pump,Steel-Braided Quick Connect high pressure hose", "src/imgs/pressure-washers-1500psi.jpg", "wheeled powerwasher black body with yellow trim"),
("powerwasher, gas, 3,400 PSI", "pressure washers","20 Volt Heavy Duty Induction Motor,General Pump Triplex Plunger Pump3,400 PSI 2.5 GPM Gas Pressure Washer,Pro-style spray wand with 5 quick connect nozzle tips", "pressure-washers-gas.jpg", "wheeled powerwasher black body with yellow trim"),
("culltivator, corded", "cultivators","16 in. 13.5 Amp Corded Cultivato, Adjustable 11-16 in. Steel Tines for Easy Tilling", "cultivator,-electric.jpg", "electric cultivator with cord, black handle, green motor housing"),
("cultivator, gas-powered, 10 inch", "cultivators","10 in. 43cc Gas 2-Cycle Cultivato, tines for tilling and 2 wheels for easy maneuverability", "cultivator-gas-10inch.jpg", "cultivator with black handles and red protective casing"),
("cultivator, gas-powered, 12 inch", "cultivators","12 in. 29cc 4-Cycle Gas Cultivator, 5 in. of tilling depth and choose 6 in, or 12 in tilling widths", "cultivator-gas-12inch.jpg", "cultivator with black handles and yellow protective casing"),
("plate compactor", "plate compactors","6 HP Kohler Vibratory Plate Compactor for Soil Compaction, Compaction depth of 3,000 lbs./ft.,21 in. x 17 in. steel base plate ", "power-plate-compactor-6hp.jpg", "large plate compacter, black, with wheel kit") 
("plate compactor 6.5hp, gas", "plate compactors","6.5 HP 4-Cycle Gas Jumping Jack Tamping Rammer Vibratory Asphalt/Soil Plate Compactor, Multi-functional usage for installations and asphalting projects", "stark-plate-compactors.jpg", "plate compactor, yellow and black, for soil and asphalt"), 
("post hole digger, manual", "post hole digger","48 in. Fiberglass Handle Post Hole Digger, High carbon steel blades with beveled edges,Strong fiberglass handles with cushion grips", "post-hole-digger-manual.jpg", "manual post hold digger with red hand grips"),
("post hole digger, gas powered", "post hole digger","55CC 1-Man Post Hole Digger with 10 in. bit", "auger-gas-powered.jpg", "gas powered auger for digging holes with red handles");

COMMIT;