BEGIN;

TRUNCATE TABLE
  tools
  RESTART IDENTITY CASCADE;

INSERT INTO tools (name, category, desc,img)
('claw hammer', 'hammers', 'fiberglass claw hammer', <img src='src/imgs/husky-claw-hammers.jpg' alt='claw hammer with fiberglass handle'> ),
('framing hammer-checkered face', 'hammers','steel checkered-face hammer',<img src='src/imgs/steel-checkered-face-hammer.jpg' alt='steel-checkered-face framing hammer'>),
('framing hammer-milled face', 'hammers','steel hammer, shock reduction, milled face',<img src='src/imgs/milled-face-framing-hammer.jpg' alt='steel-milled-face framing hammer'>),
('soft hammer, double faced', 'hammers','two sided hammer, one soft face, one hard faced with hickory handle',<img src='src/imgs/-soft-double-faced-hammer.jpg' alt='double headed hammer, one head red, one head yellow, with a hickory handle. can be  used for soft or hard needs'>),
('Engineer hammer', 'hammers','steel double sided hammer',<img src='src/imgs/engineer-hammer.jpg' alt='steel double faced engineer hammer with yellow fiberglass handle'>),
('blacksmith steel hammer', 'hammers','64 oz. steel blacksmith hammer',<img src='src/imgs/steel-blacksmith-hammer.jpg' alt='steelblacksmithing hammer with one head blunt the other comes to a point'>),
('Bricklayer hammer', 'hammers','Smooth-faced double-tempered head and decreased shock with nylon wrapped handle',<img src='src/imgs/bricklayers-hammer.jpg' alt='flat faced, hammer, in blue with shock reducing wrapped handle'>),
('Demolition hammer', 'hammers','enlarged claw, 22 oz. steel head 9.25in handle',<img src='src/imgs/demolition-hammer.jpg' alt='demolition hammer, with hollow handle, enlarged claw'>),
('tack hammer', 'hammers','magnetic, hickory handle, small double headed mallet',<img src='src/imgs/tack-hammer.jpg' alt='hickory wood handle, small, double headed mallet for tacks'>),
('Tinners hammer', 'hammers','one piece construction to set rivets,  hammer',<img src='src/imgs/Tinners-hammer.jpg' alt='one piece, polished steel hammer for setting rivets'>),
('Fence Post Pounder hammer', 'hammers','27 lb. fence post hammer',<img src='src/imgs/post-pounder-hammer.jpg' alt='Post punder hammer, with two long handles and can be used by two people'>),
('tin snips', 'cutting tools','compund action straight, right, and left cut snips',<img src='src/imgs/tin-snips.jpg' alt='yellow handled tin snips with safety latch'>),
('Pick Mattock', 'cutting tools','single injection fiberglass, 2.5 pounds',<img src='src/imgs/pick-mattock.jpg' alt='2.5 pound long black handled pick mattock'>),
('High tension hack saw', 'cutting tools','contractor grade saw, cuts metal and plastic. 45 and 90 degree angles',<img src='src/imgs/contractor-hack-saw.jpg' alt='yellow and black handled hacksaw'>),
('3in. straight cut aviation snip', 'cutting tools','forged blades and bolt lock to keep blades from loosening',<img src='src/imgs/aviation-snip.jpg' alt='red handled aviation snip'>),
('Bolt Cutters', 'cutting tools','lightweight 24 inch bolt cutters',<img src='src/imgs/bolt-cutters.jpg' alt='sblack bolt cutters, 24 inches, blue and black handles'>),
('Machete', 'cutting tools','24 inch machete, great for cutting thick brush, can be used one or two handed',<img src='src/imgs/machete.jpg' alt='24 inch machete with holes in blade and black and orange grip'>),
('Jab saw', 'cutting tools','tempered steel,punches and cuts through drywall with ease. Also great for cutting through wood and plywood.',<img src='src/imgs/jab-saw.jpg' alt='red rubber handled jab saw'>),
('Log splitter', 'cutting tools','34 in. fiberglass handle, 4lb log splitter',<img src='ssrc/imgs/log-splitter-34inch.jpg' alt='black fiberglass handled log splitter'>),
('Splitting maul', 'cutting tools','8 lb. 34inch splitting maul with fiberglass handle',<img src='src/imgs/splitting-maul-34inch.jpg' alt='black fiber glass handled 34 inch splitting maul'>),
('Cutter Mattock', 'cutting tools','fiberglass handle, 36 inches, 5lbs',<img src='src/imgs/cutter-mattock-5lbs.jpg' alt='36 inch lack fiberglass handled cutting mattock'>),
('Single Bit Axe', 'cutting tools','laser etched grip for affed control, 4 lbs, 35 in hickory axe',<img src='src/imgs/axe-4lbs.jpg' alt='35 inch hickory handled axe with laser etched handle'>),
('camp axe', 'cutting tools','1 1/4 lbs camp axe with fiberglas handle(14in.)',<img src='src/imgs/camp-axe.jpg' alt='14 inch fiberglass handle, black, camp axe'>),
('Tooth saw', 'cutting tools','15 inch tooth saw, aluminum handle',<img src='src/imgs/tooth-saw.jpg' alt='traditional hand saw, 15 inches, black and gold handle'>),
('Coping Saw', 'cutting tools','adjustable blade, allows for 360 degree cuts, heavy duty steel frame',<img src='src/imgs/coping-saw.jpg' alt='wood handled 6 inch coping saw'>),
('Cordless drill/driver, 18 volt', 'electric drills','shared with lithium ion battery, charger, and bag. Bits are seperate.',<img src='src/imgs/cordless-power-drill.jpg' alt='black and yellow drill/driver with bag, two batteries, and charger'>),
('Cordless impact driver', 'electric drills','18 volt lithium ion brushless impact driver with one battery and charger, plus bag. bits are not included.',<img src='src/imgs/cordless-impact-driver.jpg' alt='Blue and black color scheme for bag, impact driver, one battery and charger'>),
('Hammer Drills', 'electric drills','1/2 inch variable speed, reversable hammer drill, 2700 rpm amd 8 ft cord',<img src='src/imgs/hammer-drill.jpg' alt='black and gold hammer driver'>),
('Rotary hammer driver', 'electric drills','e-clutch 15 amp 1-3/4 in corded combimation hammer. 8.1 ft-lbs of impact',<img src='src/imgs/rotary-hammers.jpg' alt='red and black rotary hammer driver'>),
('Circular saw, cordless-Tool only', 'electric saws','20-Volt motor delivers up to 460 MWO and 5,150 RPM, Up to 50 degree bevel cut capacity,2-1/4 in. cutting capacity at 90 degree  ',<img src='src/imgs/cordless-circular-saw.jpg' alt='black and gold cordless circular saw'>),
('cordless 4-1/2 inch circular saw-Tool Only', 'electric saws','20-Volt motor delivers up to 800 MWO and 4500 RPM, p to 45 degree bevel cut capacity',<img src='src/imgs/circular-saw4in.jpg' alt='black and gold cordless 4 1/2inch circular saw'>),
('circular saw, corded with hard case', 'electric saws','15 Amp, 3.25 peak horsepower motor,
',<img src='src/imgs/corded-circular-saw.jpg' alt='red and silvar circular saw and hard case in red'>),
('reciprocating saw, cordless', 'electric saws','20 volt litium ion cordless recipricating saw Tool-Only. Variable speed trigger, keyless blade change',<img src='src/imgs/cordless-recipricating-saw.jpg' alt='yellow and black reciprocating saw'>),
('sawzall reciprocating saw with cord', 'electric saws','12 amps reciprocating saw, redesigned front grip, 1-11/8th in stroke length with clutch',<img src='src/imgs/corded-reciprocating-saw.jpg' alt='reg and grey reciprocating saw with cord'>),
('Table saw', 'electric saws','15 amp 10inch table saw with rolling stand, push stick, and miter gauge',<img src='src/imgs/portable-table-saws.jpg' alt='yellow and black table saw with rolling stand'>),
('jig saw, cordless', 'electric saws','18 volt litium ion battert, cordless jig saw. Works on hardwoods, metal, other hard materials. Uses t-shank jig saw blades (not included)',<img src='src/imgs/cordless-jigsaw.jpg' alt='red and black cordless jigsaw'>),
('jigsaw, corded 6.5 amp', 'electric saws','8.5 amp motor, 4 position orbital action, keyless show bevel, lever-action blade clamp and dust blower',<img src='src/imgs/corded-jigsaw.jpg' alt='black and gold corded jigsaw (blades not included'>),
('grinder, cordless', 'power grinders','18-Volt Lithium-Ion Brushless Cordless 4-1/2 in. / 5 in. Grinder with Paddle Switch (Tool-Only)',<img src='src/imgs/cordless-grinder.jpg' alt='red and black power grinder, cordless'>),
('cut off/angle grinder, cordless', 'power grinders','18-Volt LXT Lithium-Ion Brushless Cordless 4-1/2 in./5 in. Cut-Off/Angle Grinder (Tool-Only)',<img src='src/imgs/angle-grinder-cordless.jpg' alt='blue and silver cordless grinder'>),
('belt sander, cordless', 'sanders','18-Volt GEN5X Cordless Brushless 3 in. x 18 in. Belt Sander (Tool Only) with Dust Bag and (1) 80 Grit Sanding Belt, Tool-free sanding belt release for easy changes, Features an integrated vac adaptor for dust-free results',<img src='src/imgs/steel-checkered-face-hammer.jpg' alt='steel-checkered-face framing hammer'>),
('framing hammer', 'hammers','steel checkered-face hammer',<img src='src/imgs/cordless-belt-sander.jpg' alt='orange and black belt sander, cordless'>),
('belt sander, corded', 'sanders','11 Amp 4 in. x 24 in. Corded Belt Sander with Abrasive Belt, 80G Belt and Dust Bag,16.2 ft cord for maneuverability and large front grip for comfort',<img src='src/imgs/corded=belt-sander.jpg' alt='blue belt sander with red dust bag'>),
('orbital sander, corded', 'sanders','3 Amp Corded 5 in. Random Orbital Sander with AIRGUARD Technology, Airguard dust collection system gathers up to 90% of the dust, Soft start and pad brake to help prevent gouges',<img src='src/imgs/disc-orbital-sanders-corded.jpg' alt='orange orbital sander, corded'>),
('orbital sander, cordless', 'sanders','18-Volt Lithium-Ion Cordless 5 in. Random Orbit Sander (Tool-Only), 12,000 OPM Max with Variable Speed Control',<img src='src/imgs/steel-checkered-face-hammer.jpg' alt='red and black orbital sander, cordless, with battery, dustbag, and sanding pad'>),
('electric chainsaw, corded', 'chain saws','18 in. 15 Amp Self Sharpening Electric Chainsaw, features a chain that can sharpen itself. The 15 Amp high-powered motor offers fast cutting with an 18 in. (45 cm) reduced-kickback guide bar and chain.',<img src='src/imgs/electric-chainsaw-corded.jpg' alt='ssilver and black electric chain saw with cord'>),
('chainsaw, cordless', 'chainsaws','20-Volt MAX Lithium-Ion Cordless 12 in. Brushless Chainsaw w/ (1) 5.0Ah Battery and Charger, OREGON bar and chain are low-kickback and automatically oiled',<img src='ssrc/imgs/chainsaws-cordless.jpg' alt='gold and black cordless electric chainsaw'>),
('chainsaw, gas-powered', 'chainsaws','14 in. 37cc 2-Cycle Gas Chainsaw, 3-point vibration isolation increases comfort and reduces fatigue, Automatic oiler for smooth operation  ',<img src='src/imgs/gas-chainsaw.jpg' alt='green and black gas powered chainsaw, 14inch bar'>),
('powerwasher, electric, 2,000 PSI', 'pressure washers','1.2 GPM Electric Pressure Washer, Powerful 13 Amp Motor Handles Tough Jobs',<img src='src/imgs/electric-power-washer.jpg' alt='powerwasher black handled, white hose, green body on wheels'>),
('powerwasher, electric, 1500 PSI', 'pressure washers','120 Volt Heavy Duty Induction Motor,General Pump Triplex Plunger Pump,Steel-Braided Quick Connect high pressure hose',<img src='src/imgs/pressure-washers-1500psi.jpg' alt='wheeled powerwasher black body with yellow trim'>),
('powerwasher, gas, 3,400 PSI', 'pressure washers','20 Volt Heavy Duty Induction Motor,General Pump Triplex Plunger Pump3,400 PSI 2.5 GPM Gas Pressure Washer,Pro-style spray wand with 5 quick connect nozzle tips',<img src='src/imgs/pressure-washers-gas.jpg' alt='wheeled powerwasher black body with yellow trim'>),
('culltivator, corded', 'cultivators','16 in. 13.5 Amp Corded Cultivato, Adjustable 11-16 in. Steel Tines for Easy Tilling',<img src='src/imgs/cultivator,-electric.jpg' alt='electric cultivator with cord, black handle, green motor housing'>),
('cultivator, gas-powered, 10 inch', 'cultivators','10 in. 43cc Gas 2-Cycle Cultivato, tines for tilling and 2 wheels for easy maneuverability',<img src='src/imgs/cultivator-gas-10inch.jpg' alt='cultivator with black handles and red protective casing'>),
('cultivator, gas-powered, 12 inch', 'cultivators','12 in. 29cc 4-Cycle Gas Cultivator, 5 in. of tilling depth and choose 6 in, or 12 in tilling widths',<img src='src/imgs/cultivator-gas-12inch.jpg' alt='cultivator with black handles and yellow protective casing'>),
('plate compactor', 'plate compactors','6 HP Kohler Vibratory Plate Compactor for Soil Compaction, Compaction depth of 3,000 lbs./ft.,21 in. x 17 in. steel base plate ',<img src='src/imgs/power-plate-compactor-6hp.jpg' alt='large plate compacter, black, with wheel kit'>) 
('plate compactor 6.5hp, gas', 'plate compactors','6.5 HP 4-Cycle Gas Jumping Jack Tamping Rammer Vibratory Asphalt/Soil Plate Compactor, Multi-functional usage for installations and asphalting projects',<img src='src/imgs/8stark-plate-compactors.jpg' alt='plate compacto, yellow and black, for soil and asphalt'>), 
('post hole digger, manual', 'post hole digger','48 in. Fiberglass Handle Post Hole Digger, High carbon steel blades with beveled edges,Strong fiberglass handles with cushion grips',<img src='src/imgs/post-hole-digger-manual.jpg' alt='manual post hold digger with red hand grips'>),
('post hole digger, gas powered', 'post hole digger','55CC 1-Man Post Hole Digger with 10 in. bit',<img src='src/imgs/auger-gas-powered.jpg' alt='gas powered auger for digging holes with red handles'>);

COMMIT;